# Generated by Django 4.2 on 2023-04-16 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_client_employees_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email_id',
            field=models.CharField(max_length=25),
        ),
    ]
