# Generated by Django 4.2 on 2023-04-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_client_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
